# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Thanh/Desktop/MIST_Nexys4/project_1/project_1.srcs/sources_1/ip/output_weight_3/output_weight_3.xci
# IP: The module: 'output_weight_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Thanh/Desktop/MIST_Nexys4/project_1/project_1.srcs/sources_1/ip/output_weight_3/output_weight_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'output_weight_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/Thanh/Desktop/MIST_Nexys4/project_1/project_1.srcs/sources_1/ip/output_weight_3/output_weight_3.xci
# IP: The module: 'output_weight_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Thanh/Desktop/MIST_Nexys4/project_1/project_1.srcs/sources_1/ip/output_weight_3/output_weight_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'output_weight_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
