# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/coe_files/python_hidden_weight.coe
add_files C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/coe_files/output_weight_0.coe
add_files C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/coe_files/output_weight_1.coe
add_files C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/coe_files/output_weight_2.coe
add_files C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/coe_files/output_weight_3.coe
add_files C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/coe_files/output_weight_4.coe
add_files C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/coe_files/test_input.coe
add_files C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/coe_files/single_digit.coe
add_files C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/coe_files/back_ground.coe
add_files C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/coe_files/hidden_weight_0.coe
add_files C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/coe_files/hidden_weight_1.coe
add_files -quiet c:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/hidden_layer_weight/hidden_layer_weight.dcp
set_property used_in_implementation false [get_files c:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/hidden_layer_weight/hidden_layer_weight.dcp]
add_files -quiet c:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/output_weight_0/output_weight_0.dcp
set_property used_in_implementation false [get_files c:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/output_weight_0/output_weight_0.dcp]
add_files -quiet c:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/output_weight_1/output_weight_1.dcp
set_property used_in_implementation false [get_files c:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/output_weight_1/output_weight_1.dcp]
add_files -quiet c:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/output_weight_2/output_weight_2.dcp
set_property used_in_implementation false [get_files c:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/output_weight_2/output_weight_2.dcp]
add_files -quiet c:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/output_weight_3/output_weight_3.dcp
set_property used_in_implementation false [get_files c:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/output_weight_3/output_weight_3.dcp]
add_files -quiet c:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/output_weight_4/output_weight_4.dcp
set_property used_in_implementation false [get_files c:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/output_weight_4/output_weight_4.dcp]
add_files -quiet c:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/data_and_label/data_and_label.dcp
set_property used_in_implementation false [get_files c:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/data_and_label/data_and_label.dcp]
add_files -quiet c:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files c:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp]
add_files -quiet C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/background_ROM/background_ROM.dcp
set_property used_in_implementation false [get_files C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/background_ROM/background_ROM.dcp]
add_files -quiet c:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/hidden_weight_rom/hidden_weight_rom.dcp
set_property used_in_implementation false [get_files c:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/hidden_weight_rom/hidden_weight_rom.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/imports/new/sigmoid_function.v
  C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/imports/new/neuron.v
  C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/imports/new/debounce.v
  C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/imports/new/neuron_network_sigmoid.v
  C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/imports/new/VGA_Controller.v
  C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/imports/new/data_select.v
  C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/imports/new/sevensegment.v
  C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/imports/new/num_select.v
  C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/imports/new/Nexys4_Top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/constrs_1/imports/project1_release/n4DDRfpga_withvideo.xdc
set_property used_in_implementation false [get_files C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/constrs_1/imports/project1_release/n4DDRfpga_withvideo.xdc]


synth_design -top Nexys4_Top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Nexys4_Top.dcp

catch { report_utilization -file Nexys4_Top_utilization_synth.rpt -pb Nexys4_Top_utilization_synth.pb }
