# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Thanh/Desktop/MIST_Nexys4/project_1/project_1.srcs/sources_1/ip/hidden_weight_rom/hidden_weight_rom.xci
# IP: The module: 'hidden_weight_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Thanh/Desktop/MIST_Nexys4/project_1/project_1.srcs/sources_1/ip/hidden_weight_rom/hidden_weight_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hidden_weight_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Thanh/Desktop/MIST_Nexys4/project_1/project_1.srcs/sources_1/ip/hidden_weight_rom/hidden_weight_rom.xci
# IP: The module: 'hidden_weight_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Thanh/Desktop/MIST_Nexys4/project_1/project_1.srcs/sources_1/ip/hidden_weight_rom/hidden_weight_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hidden_weight_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
