# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/background_ROM/background_ROM.xci
# IP: The module: 'background_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/background_ROM/background_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'background_ROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/background_ROM/background_ROM.xci
# IP: The module: 'background_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Thanh/Documents/GitHub/MNIST_Nexys4/MNIST_Nexys4DDR/project_1/project_1.srcs/sources_1/ip/background_ROM/background_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'background_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
